# Separating code from configuration.
# Please DO NOT EDIT this file.
class Config
    class << self ; attr_accessor :vars ; end
    self.vars = '.'
end

require './conf.rb'         # <--- as a user, THIS is the file you want to edit 
require './src/main.rb'
